repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v1.0.0
  hooks:
  - id: commitlint
    stages:
    - commit-msg

- repo: https://github.com/ejba/pre-commit-maven
  rev: v1.0.0
  hooks:
  - id: maven
    args:
    - clean
    - compile
  - id: maven-spotless-apply

- repo: local
  hooks:
  - id: cx-secret-detection
    name: Cx Secret Detection
    entry: cx
    description: Run Cx CLI secret detection
    stages:
    - pre-commit
    args:
    - hooks
    - pre-commit
    - secrets-scan
    language: system
    minimum_pre_commit_version: "3.2.0"
